# MCPHost Configuration
mcpServers:
  roles:
    type: local
    command: ["./server/server.py"]
    allowedTools: ["run_system_role", "list_available_roles", "get_role_documentation"]

model: "ollama:gpt-oss:20b"
system-prompt: "./system-prompt.md"
temperature: 0.2
max-tokens: 2048
